name: graphql_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

  material_design_icons_flutter: ^4.0.5045

  graphql_flutter: ^3.0.0
  gql_code_gen: ^0.1.5
  http: ^0.12.0+4
  onesignal_flutter: ^2.3.3
  flutter_dotenv: ^2.1.0
  flutter_mobx: ^0.3.6
  provider: ^4.0.1



dev_dependencies:
  mobx_codegen: ^0.4.0+1
  build_runner: ^1.7.3

  flutter_test:
    sdk: flutter


assets:
    - .env

flutter:


  uses-material-design: true

